version: '3'

services:
  get-events:
    build:
      context: ./handlers
      args:
        handler: get-events
    ports:
      - 9000:8080
    environment:
      MONGODB_URI: mongodb://db:27017
    depends_on:
      - db
  add-event:
    build:
      context: ./handlers
      args:
        handler: add-event
    ports:
      - 9001:8080
    environment:
      MONGODB_URI: mongodb://db:27017
    depends_on:
      - db
  db:
    image: mongo:4.4.5
    environment:
      MONGO_INITDB_DATABASE: events
