version: '3'

services:
  get-events:
    build:
      context: ./handlers
      args:
        handler: get-events
    environment:
      MONGODB_URI: mongodb://db:27017
    depends_on:
      - db
  add-event:
    build:
      context: ./handlers
      args:
        handler: add-event
    environment:
      MONGODB_URI: mongodb://db:27017
    depends_on:
      - db
  db:
    image: mongo:4.4.5
    environment:
      MONGO_INITDB_DATABASE: events
  api-gateway:
    image: nginx:1.20.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./local-api-gateway:/etc/nginx:ro
